### ISSUE TITLE
 Unable to download node

### ISSUE THREAD

**Issue by reutopiaer** [deis/example-nodejs-express#8]
$git push deis master

-----> Installing binaries
       engines.node (package.json):  4.2.x
       engines.npm (package.json):   unspecified (use default)

```
   Resolving node version 4.2.x via semver.io...
   Downloading and installing node ...
   Unable to download node ; does it exist?
```

-----> Build failed

```
   We're sorry this build is failing! You can troubleshoot common issues here:
   https://devcenter.heroku.com/articles/troubleshooting-node-deploys

   If you're stuck, please submit a ticket so we can help:
   https://help.heroku.com/

   Love,
   Heroku
```

**Comment by Joshua-Anderson** [comment]
@reutopiaer What version of deis are you using? Did you get this error when deploying the example nodejs app?

**Comment by reutopiaer** [comment]
$deis -v
2.2.0-32177aa 

$git push deis master
Counting objects: 195, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (88/88), done.
Writing objects: 100% (195/195), 35.34 KiB | 0 bytes/s, done.
Total 195 (delta 104), reused 195 (delta 104)
Starting build... but first, coffee!                                           
...
-----> Node.js app detected

-----> Creating runtime environment

```
   NPM_CONFIG_LOGLEVEL=error
   NPM_CONFIG_PRODUCTION=true
   NODE_ENV=production
   NODE_MODULES_CACHE=true
```

-----> Installing binaries
       engines.node (package.json):  4.2.x
       engines.npm (package.json):   unspecified (use default)

```
   Resolving node version 4.2.x via semver.io...
   Downloading and installing node ...
   Unable to download node ; does it exist?
```

-----> Build failed

```
   We're sorry this build is failing! You can troubleshoot common issues he
```

e:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

```
   If you're stuck, please submit a ticket so we can help:
   https://help.heroku.com/

   Love,
   Heroku
```

**Comment by bacongobbler** [comment]
9 times out of 10 this is a connection issue/DNS issue. When I hit this problem, the DNS server provided by my ISP redirected the requests incorrectly. The resolution for me was to change my DNS settings on the host to hit Google's DNS server (8.8.8.8 or 8.8.4.4), re-provision the cluster and suddenly my Vagrant cluster worked again.

What provider are you using to install Kubernetes, and what version of Kubernetes are you running? Is this on Vagrant or on a public cloud provider like AWS?

**Comment by reutopiaer** [comment]
@bacongobbler 

local area network   kubernetes/cluster/vagrant   

follow document:  https://deis.com/docs/workflow/quickstart/provider/vagrant/install-vagrant/

/etc/dnsmasq.conf  add:  address=/nip.io/10.247.3.77

$host 10.247.3.77.nip.io
10.247.3.77.nip.io has address 10.247.3.77
$ host something-random.10.247.3.77.nip.io
something-random.110.247.3.77.nip.io has address 10.247.3.77
$ curl http://deis.10.247.3.77.nip.io/v2/ && echo
{"detail":"Authentication credentials were not provided."}

**Comment by reutopiaer** [comment]
opps，I made a big mistake，when I stop dnsmsaq the problem is solved. Sorry for everyone!
